version: "3.9"

services:
    shopzawy.api:
        container_name: shopizawy.Api
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ${HTTPS_CERT_PATH}:/https:ro
        ports:
            - "8080:8080"
            - "8081:8081"
        environment:
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnet-dev.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=${HTTPS_CERT_PASSWORD}
        env_file:
            - .env
    shopzawy.database:
        image: postgres:latest
        container_name: shopizawy.Database
        environment:
            - POSTGRES_DB=ShopizawyDb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=784512
        volumes:
            - ./.containers/db:/var/lib/postgresql/data
        ports:
            - 5432:5432
