version: "3.9"

services:
    shopzawy.api:
        container_name: shopizawy.Api
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ${HTTPS_CERT_PATH}:/https:ro
        ports:
            - "8080:8080"
            - "8081:8081"
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnet-dev.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=${HTTPS_CERT_PASSWORD}
            - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID}
            - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
            - Authentication__Facebook__AppId=${FACEBOOK_APP_ID}
            - Authentication__Facebook__AppSecret=${FACEBOOK_APP_SECRET}
            - Jwt__Issuer=${JWT_ISSUER}
            - Jwt__Audience=${JWT_AUDIENCE}
            - Jwt__SecretKey=${JWT_SECRETKEY}
            - Jwt__LifeTimeInMinutes=${JWT_LIFETIME_IN_MINUTES}
            - ConnectionStrings__ShopizawyDb=Host=shopzawy.database;Port=5432;Database=ShopizawyDb;Username=postgres;Password=784512
    shopzawy.database:
        image: postgres:latest
        container_name: shopizawy.Database
        environment:
            - POSTGRES_DB=ShopizawyDb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=784512
        volumes:
            - ./.containers/db:/var/lib/postgresql/data
        ports:
            - 5432:5432
