// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Users.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Users.Infrastructure.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20250614132553_addedPermissionsToGuest")]
    partial class addedPermissionsToGuest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Common.Infrastructure.Inbox.InboxConsumerMessage", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HandlerName")
                        .HasColumnType("text")
                        .HasColumnName("handler_name");

                    b.HasKey("id", "HandlerName")
                        .HasName("pk_inbox_consumer_message");

                    b.ToTable("inbox_consumer_message", "users");
                });

            modelBuilder.Entity("Modules.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "users");
                });

            modelBuilder.Entity("Modules.Common.Infrastructure.Outbox.OutboxConsumerMessage", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HandlerName")
                        .HasColumnType("text")
                        .HasColumnName("handler_name");

                    b.HasKey("id", "HandlerName")
                        .HasName("pk_outbox_consumer_message");

                    b.ToTable("outbox_consumer_message", "users");
                });

            modelBuilder.Entity("Modules.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "users");
                });

            modelBuilder.Entity("Modules.Users.Domain.Entities.Permission", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Module")
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.HasKey("Name")
                        .HasName("pk_permission");

                    b.ToTable("permission", "users");

                    b.HasData(
                        new
                        {
                            Name = "user:create",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Users"
                        },
                        new
                        {
                            Name = "user:role:update",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Users"
                        },
                        new
                        {
                            Name = "role:read",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Users"
                        },
                        new
                        {
                            Name = "role:create",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Users"
                        },
                        new
                        {
                            Name = "role:permission:update",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Users"
                        },
                        new
                        {
                            Name = "permission:read",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Users"
                        },
                        new
                        {
                            Name = "permission:create",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Users"
                        },
                        new
                        {
                            Name = "permission:update",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Users"
                        },
                        new
                        {
                            Name = "auth:login",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Users"
                        },
                        new
                        {
                            Name = "banner:create",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "banner:read",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "banner:delete",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "brand:create",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "brand:read",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "brand:update",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "category:create",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "category:update",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "category:read",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "category:delete",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "color:create",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "color:read",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "product:create",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "product:item:create",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "product:item:read",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "product:item:delete",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "spec:create",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "spec:read",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "spec:update",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "vendor:create",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "vendor:update",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        },
                        new
                        {
                            Name = "vendor:read",
                            Active = true,
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Module = "Orders"
                        });
                });

            modelBuilder.Entity("Modules.Users.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.HasKey("Name")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", "users");

                    b.HasData(
                        new
                        {
                            Name = "Guest",
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Name = "Admin",
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Name = "Default",
                            CreatedOnUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Modules.Users.Domain.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_id");

                    b.Property<string>("PermissionId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permission");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permission_permission_id");

                    b.ToTable("role_permission", "users");

                    b.HasData(
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "banner:create"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "banner:read"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "banner:delete"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "brand:create"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "brand:read"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "brand:update"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "category:create"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "category:update"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "category:read"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "category:delete"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "color:create"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "color:read"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "product:create"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "product:item:create"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "product:item:read"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "product:item:delete"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "spec:create"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "spec:read"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "spec:update"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "vendor:create"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "vendor:update"
                        },
                        new
                        {
                            RoleId = "Admin",
                            PermissionId = "vendor:read"
                        },
                        new
                        {
                            RoleId = "Default",
                            PermissionId = "banner:read"
                        },
                        new
                        {
                            RoleId = "Default",
                            PermissionId = "brand:read"
                        },
                        new
                        {
                            RoleId = "Default",
                            PermissionId = "category:read"
                        },
                        new
                        {
                            RoleId = "Default",
                            PermissionId = "color:read"
                        },
                        new
                        {
                            RoleId = "Default",
                            PermissionId = "product:item:read"
                        },
                        new
                        {
                            RoleId = "Default",
                            PermissionId = "spec:read"
                        },
                        new
                        {
                            RoleId = "Default",
                            PermissionId = "vendor:read"
                        },
                        new
                        {
                            RoleId = "Guest",
                            PermissionId = "banner:read"
                        },
                        new
                        {
                            RoleId = "Guest",
                            PermissionId = "brand:read"
                        },
                        new
                        {
                            RoleId = "Guest",
                            PermissionId = "category:read"
                        },
                        new
                        {
                            RoleId = "Guest",
                            PermissionId = "product:item:read"
                        },
                        new
                        {
                            RoleId = "Guest",
                            PermissionId = "user:create"
                        },
                        new
                        {
                            RoleId = "Guest",
                            PermissionId = "auth:login"
                        });
                });

            modelBuilder.Entity("Modules.Users.Domain.Entities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpireDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_date_utc");

                    b.Property<int>("TokenType")
                        .HasColumnType("integer")
                        .HasColumnName("token_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_token_user_id");

                    b.HasIndex("Value", "TokenType")
                        .IsUnique()
                        .HasDatabaseName("ix_token_value_token_type");

                    b.ToTable("token", "users");
                });

            modelBuilder.Entity("Modules.Users.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_creation");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", "users");
                });

            modelBuilder.Entity("Modules.Users.Domain.Entities.UserRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RoleId", "UserId")
                        .HasName("pk_user_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_role_user_id");

                    b.ToTable("user_role", "users");
                });

            modelBuilder.Entity("Modules.Users.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Modules.Users.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_permission_permission_id");

                    b.HasOne("Modules.Users.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Modules.Users.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Modules.Users.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_roles_role_id");

                    b.HasOne("Modules.Users.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Modules.Users.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Modules.Users.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Modules.Users.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
